# Generated by Django 6.0.1 on 2026-02-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.etudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.ue')),
            ],
            options={
                'unique_together': {('etudiant', 'ue')},
            },
        ),
    ]
