# Generated by Django 6.0.1 on 2026-02-03 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_departement_niveau_remove_note_valeur_note_cc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='ues', to=settings.AUTH_USER_MODEL),
        ),
    ]
