# Generated by Django 6.0.1 on 2026-02-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_ue_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ue',
            old_name='teachers',
            new_name='instructors',
        ),
    ]
