# Generated by Django 6.0.1 on 2026-02-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_rename_teachers_ue_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1),
        ),
    ]
